[project]
name = "dsa-mojo"
version = "0.1.0"
description = "DSA implementations in Mojo 1.1"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "max>=26.6.0",
    "modular>=26.6.0",
    "black>=25.1.0",
    "flake8>=7.3.0",
    "isort>=6.0.1",
    "pre-commit>=4.2.0",
    "ruff>=0.12.0",
]
